language:
  - c
  - cpp

cache: ccache

compiler:
  - gcc

before_script:
  - psql -c 'create database libpq_demo;' -U postgres
  - git clone https://github.com/zeromq/libzmq
  - mkdir -p libzmq/build && cd libzmq/build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=../../zeormq .. && make -j 4 && cd ../../

script:
  - make clean -C c && make all -C c
  - make clean -C cpp && make all -C cpp
  - cd ./c && sh run.sh && cd ..
  - cd ./cpp && sh run.sh && cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)
