language:
  - c
  - cpp

cache: ccache

compiler:
  - gcc

before_script:
  - psql -c 'create database libpq_demo;' -U postgres
  - git clone git clone https://github.com/zeromq/libzmq $TRAVIS_BUILD_DIR/libzmq
  - mkdir -p $TRAVIS_BUILD_DIR/libzmq/build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=$TRAVIS_BUILD_DIR/zeormq .. && make -C $TRAVIS_BUILD_DIR/libzmq/build -j 4

script:
  - make clean -C c && make all -C c
  - make clean -C cpp && make all -C cpp
  - cd ./c && sh run.sh && cd ..
  - cd ./cpp && sh run.sh && cd ..

after_success:
  - bash <(curl -s https://codecov.io/bash)
